name: CI
on:
  push:
    branches:
      - "*"
jobs:
  directory:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: matrix
        run: echo "matrix=$(find `pwd` -name "kustomization.yaml" -exec dirname {} \; | jq -c .)" >> $GITHUB_OUTPUT

  ci:
    name: CI
    runs-on: ubuntu-latest
    if: ${{ needs.directories.outputs.matrix != '[]' }}
    strategy:
      max-parallel: 1
      matrix:
        directory: ${{fromJson(needs.directory.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '5.1.0'
          kustomize_build_dir: ${{ matrix.directories }}
          kustomize_comment: true
          #kustomize_output_file: "gitops/rendered.yaml"
          kustomize_build_options: "--enable-helm"
          enable_alpha_plugins: false
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
