name: CI
on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: imranismail/setup-kustomize@master
        with:
          kustomize-version: "5.1.0"
      - shell: bash
        run:  mkdir .manifests; find . -type d | grep overlays/ | xargs -I{} sh -c 'kustomize build {} > .manifests/$(echo {} | tr / _ | tr . _).yaml'
      - uses: ./
