name: CI
on:
  push:
    branches:
      - "*"
jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: matrix
        run: |
          directories=$(find `pwd` -name "kustomization.yaml" -exec dirname {} \; | jq -Rc . | jq -cs .)
          echo "matrix=${directories}" 
          echo "matrix=${directories}" >> $GITHUB_OUTPUT

  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        directory: ${{ fromJSON(needs.directories.outputs.directories) }}
    steps:
      - uses: actions/checkout@v3
      - uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '5.1.0'
          kustomize_build_dir: ${{ matrix.directory }}
          kustomize_comment: true
          #kustomize_output_file: "gitops/rendered.yaml"
          kustomize_build_options: "--enable-helm"
          enable_alpha_plugins: false
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
