name: CI
on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      K8S_CI_MANIFESTS_PATH: .manifests
    steps:
      - uses: actions/checkout@v3
      - uses: imranismail/setup-kustomize@master
        with:
          kustomize-version: "5.1.0"
      - shell: bash
        run:  mkdir ${K8S_CI_MANIFESTS_PATH}; find . -type d | grep overlays/ | xargs -I{} sh -c 'kustomize build {} > ${K8S_CI_MANIFESTS_PATH}/$(echo {} | tr / _ | tr . _).yaml'
      - uses: ./
