name: CI
on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      K8S_CI_MANIFESTS_PATH: .manifests
    steps:
      - uses: actions/checkout@v3
      - uses: ./
