name: CI
on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: imranismail/setup-kustomize@master
        with:
          kustomize-version: "5.1.0"
      - run: set -o pipefail; mkdir .manifests; find . -type d | grep overlays/ | xargs -I{} sh -c 'kustomize build {} > .manifests/$(echo {} | tr / _ | tr . _).yaml'
      - uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' ./.manifests/"
      - uses: FairwindsOps/pluto/github-action@master
      - run: pluto detect-files -o wide -d .manifests/
      - uses: fairwindsops/polaris/.github/actions/setup-polaris@master

